### ISSUE TITLE
Add support for ESP32-S3

### ISSUE THREAD

**Issue by Kampi** [espressif/esp-bootloader-plus#4]
I´m looking for a solution to use the Bootloader-Plus with an ESP32-S3 and found this in`bootloader_custom_malloc.c`:

```
#define XZ_BOOT_HEAP_ADDRESS                                                        SOC_DRAM_LOW // (0x3FC7C000 + 0x4000) // for esp32c3 chip, you can use the free space form this address, pay attention your chip for this
static uint8_t* heap_pool = (uint8_t*)XZ_BOOT_HEAP_ADDRESS; // now these memory is not been used, the address have to be 4-byte aligned.
static uint32_t heap_used_offset = 0;
```

The address is somewhere in the DRAM, but I can not figure out how this address was chosen, How is this address defined and how can I find the correct address for the ESP32-S3?

**Comment by WangYuxin-esp** [comment]
`SOC_DRAM_LOW` address is defined by the system itself. For ESP32-S3, please refer to [here](https://github.com/espressif/esp-idf/blob/release/v4.4/components/soc/esp32s3/include/soc/soc.h#L255). Sorry, the relevant comments in the code have caused you trouble.
In addition, I used ESP32S3 to test the compressed ota, and it works normally.

**Comment by Kampi** [comment]
Hi @WangYuxin-esp,

thanks! I guess it´s enough to change the target to ESP32-S3 and compile the code again.
